version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - '2181:2181'
    networks:
      - bigdata

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - bigdata

  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    environment:
      - INIT_DAEMON_STEP=setup_spark
    ports: 
      - '8080:8080'
      - '7077:7077'
    networks:
      - bigdata

  spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - '8081:8081'
    environment:
      - 'SPARK_MASTER=spark://spark-master:7077'
    networks:
      - bigdata

  spark-worker-2:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - '8082:8081'
    environment:
      - 'SPARK_MASTER=spark://spark-master:7077'
    networks:
      - bigdata

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    networks:
      - bigdata

  datanode-1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode-1
    restart: always
    volumes:
      - hadoop_datanode_1:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: 'namenode:9870'
    env_file:
      - ./hadoop.env
    networks:
      - bigdata
  
  datanode-2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode-2
    restart: always
    volumes:
      - hadoop_datanode_2:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: 'namenode:9870'
    env_file:
      - ./hadoop.env
    networks:
      - bigdata

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    restart: always
    ports:
      - 9864:9864
    environment:
      SERVICE_PRECONDITION: 'namenode:9000 namenode:9870 datanode:9864'
    env_file:
      - ./hadoop.env
    networks:
      - bigdata

  nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager
    restart: always
    ports:
      - 8088:8088
    environment:
      SERVICE_PRECONDITION: 'namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088'
    env_file:
      - ./hadoop.env
    networks:
      - bigdata

networks:
  bigdata:
    driver: bridge

volumes:
  spark-master:
  kafka:
  zookeeper:
  hadoop_namenode:
  hadoop_datanode_1:
  hadoop_datanode_2: